export const FETCH_WEATHER_CITY_REQUEST = 'FETCH_WEATHER_CITY_REQUEST';
export const FETCH_WEATHER_CITY_SUCCESS = 'FETCH_WEATHER_CITY_SUCCESS';
export const FETCH_WEATHER_CITY_FAILURE = 'FETCH_WEATHER_CITY_FAILURE';